# Generated by Django 4.2.7 on 2023-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
                ('control_valve', models.BooleanField(default=False, verbose_name='Control Valve')),
                ('auto_detect', models.BooleanField(default=False, verbose_name='Auto Detect')),
            ],
            options={
                'verbose_name_plural': '控制設置',
            },
        ),
        migrations.CreateModel(
            name='LocalWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humd', models.FloatField(null=True, verbose_name='相對濕度')),
                ('temp', models.FloatField(null=True, verbose_name='溫度')),
                ('elev', models.FloatField(null=True, verbose_name='高度')),
                ('time', models.DateTimeField(unique=True, verbose_name='資料觀測時間')),
                ('pres', models.FloatField(null=True, verbose_name='測站氣壓')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
            ],
            options={
                'verbose_name': '本地天氣',
                'verbose_name_plural': '本地天氣數據',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
                ('this_month_rainfall_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='This Month Rainfall Level')),
                ('this_month_temperature_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='This Month Temperature Level')),
                ('three_months_rainfall_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='Three Months Rainfall Level')),
                ('three_months_temperature_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='Three Months Temperature Level')),
                ('one_year_rainfall_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='One Year Rainfall Level')),
                ('one_year_temperature_level', models.IntegerField(choices=[(1, '等级 1'), (2, '等级 2'), (3, '等级 3'), (4, '等级 4'), (5, '等级 5')], verbose_name='One Year Temperature Level')),
            ],
            options={
                'verbose_name': '天氣狀態',
                'verbose_name_plural': '天氣狀態',
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humd', models.FloatField(null=True, verbose_name='相對濕度')),
                ('temp', models.FloatField(null=True, verbose_name='溫度')),
                ('elev', models.FloatField(null=True, verbose_name='高度')),
                ('time', models.DateTimeField(unique=True, verbose_name='資料觀測時間')),
                ('pres', models.FloatField(null=True, verbose_name='測站氣壓')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
                ('h_24r', models.FloatField(null=True, verbose_name='日累積雨量')),
            ],
            options={
                'verbose_name': '氣象觀測',
                'verbose_name_plural': '氣象觀測',
            },
        ),
    ]
