# Generated by Django 4.2.7 on 2023-11-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localweather',
            name='auto_detect',
            field=models.BooleanField(default=False, verbose_name='自動判斷'),
        ),
        migrations.AddField(
            model_name='localweather',
            name='control_valve',
            field=models.BooleanField(default=False, verbose_name='控制水閘'),
        ),
    ]
