# Generated by Django 4.2.7 on 2023-11-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0002_localweather_auto_detect_localweather_control_valve'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='縣市')),
                ('control_valve', models.BooleanField(default=False, verbose_name='Control Valve')),
                ('auto_detect', models.BooleanField(default=False, verbose_name='Auto Detect')),
            ],
            options={
                'verbose_name_plural': '控制設置',
            },
        ),
        migrations.RemoveField(
            model_name='localweather',
            name='auto_detect',
        ),
        migrations.RemoveField(
            model_name='localweather',
            name='control_valve',
        ),
    ]
