# Generated by Django 4.2.7 on 2023-11-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0003_controlsettings_remove_localweather_auto_detect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localweather',
            old_name='CITY',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='localweather',
            old_name='ELEV',
            new_name='elev',
        ),
        migrations.RenameField(
            model_name='localweather',
            old_name='HUMD',
            new_name='humd',
        ),
        migrations.RenameField(
            model_name='localweather',
            old_name='PRES',
            new_name='pres',
        ),
        migrations.RenameField(
            model_name='localweather',
            old_name='TEMP',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='localweather',
            old_name='TIME',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='CITY',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='ELEV',
            new_name='elev',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='H_24R',
            new_name='h_24r',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='HUMD',
            new_name='humd',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='PRES',
            new_name='pres',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='TEMP',
            new_name='temp',
        ),
        migrations.RenameField(
            model_name='weatherobservation',
            old_name='TIME',
            new_name='time',
        ),
    ]
