# Generated by Django 4.2.7 on 2023-11-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmInfo', '0004_rename_city_localweather_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': '天氣狀態', 'verbose_name_plural': '天氣狀態'},
        ),
        migrations.RemoveField(
            model_name='weather',
            name='month',
        ),
    ]
